import {
  ChartColumnBigIcon,
  DatabaseIcon,
  TrendingUpIcon,
  WandSparklesIcon,
  ZapIcon,
} from 'lucide-react';

export const FEATURES = [
  {
    title: 'Enhance User Experience',
    description:
      'Efficiently manage user data and interactions with advanced AI tools',
    icon: WandSparklesIcon,
    image: '/images/feature-two.svg',
  },
  {
    title: 'Comprehensive Insights',
    description:
      'Gain deep insights into your audience and campaign performance',
    icon: ChartColumnBigIcon,
    image: '/images/feature-one.svg',
  },
  {
    title: 'Data Management',
    description: 'Manage your data with ease and efficiency',
    icon: DatabaseIcon,
    image: '/images/feature-three.svg',
  },
  {
    title: 'Real-Time Analytics',
    description: 'Track and analyze your marketing performance in real-time',
    icon: TrendingUpIcon,
    image: '/images/feature-four.svg',
  },
  {
    title: 'Dynamic Optimization',
    description: 'AI-powered optimization for smarter marketing',
    icon: ZapIcon,
    image: '/images/feature-five.svg',
  },
];
const attendanceChartData = [
  { month: 'June', attendance: 22 },
  { month: 'July', attendance: 24 },
  { month: 'August', attendance: 23 },
  { month: 'September', attendance: 26 },
  { month: 'October', attendance: 20 },
  { month: 'November', attendance: 25 },
  { month: 'December', attendance: 18 },
  { month: 'January', attendance: 23 },
  { month: 'February', attendance: 22 },
  { month: 'March', attendance: 19 },
];

// Mock attendance data
const attendanceData = [
  {
    id: 1,
    date: '2025-03-10',
    student: 'Alex Johnson',
    rollNumber: 'S001',
    section: 'A',
    status: 'present',
  },
  {
    id: 2,
    date: '2025-03-10',
    student: 'Maria Garcia',
    rollNumber: 'S002',
    section: 'A',
    status: 'absent',
  },
  {
    id: 3,
    date: '2025-03-10',
    student: 'James Wilson',
    rollNumber: 'S003',
    section: 'A',
    status: 'late',
  },
  {
    id: 4,
    date: '2025-03-10',
    student: 'Sarah Brown',
    rollNumber: 'S004',
    section: 'A',
    status: 'present',
  },
  {
    id: 5,
    date: '2025-03-10',
    student: 'David Lee',
    rollNumber: 'S005',
    section: 'A',
    status: 'present',
  },
  {
    id: 6,
    date: '2025-03-09',
    student: 'Alex Johnson',
    rollNumber: 'S001',
    section: 'A',
    status: 'present',
  },
  {
    id: 7,
    date: '2025-03-09',
    student: 'Maria Garcia',
    rollNumber: 'S002',
    section: 'A',
    status: 'present',
  },
  {
    id: 8,
    date: '2025-03-09',
    student: 'James Wilson',
    rollNumber: 'S003',
    section: 'A',
    status: 'present',
  },
  {
    id: 9,
    date: '2025-03-09',
    student: 'Sarah Brown',
    rollNumber: 'S004',
    section: 'A',
    status: 'absent',
  },
  {
    id: 10,
    date: '2025-03-09',
    student: 'David Lee',
    rollNumber: 'S005',
    section: 'A',
    status: 'late',
  },
];

const mockSectionAttendance = [
  {
    id: '1',
    section: 'Grade 1 - Section A',
    grade: 'Grade 1',
    date: '2025-03-20',
    reportedBy: 'John Smith',
    status: 'completed',
    percentage: 100,
    studentsPresent: 25,
    totalStudents: 25,
  },
  {
    id: '2',
    section: 'Grade 1 - Section B',
    grade: 'Grade 1',
    date: '2025-03-20',
    reportedBy: 'Jane Doe',
    status: 'completed',
    percentage: 96,
    studentsPresent: 24,
    totalStudents: 25,
  },
  {
    id: '3',
    section: 'Grade 2 - Section A',
    grade: 'Grade 2',
    date: '2025-03-20',
    reportedBy: 'Michael Johnson',
    status: 'pending',
    percentage: 0,
    studentsPresent: 0,
    totalStudents: 28,
  },
  {
    id: '4',
    section: 'Grade 2 - Section B',
    grade: 'Grade 2',
    date: '2025-03-20',
    reportedBy: 'Sarah Williams',
    status: 'in-progress',
    percentage: 68,
    studentsPresent: 17,
    totalStudents: 25,
  },
  {
    id: '5',
    section: 'Grade 3 - Section A',
    grade: 'Grade 3',
    date: '2025-03-20',
    reportedBy: 'Robert Brown',
    status: 'completed',
    percentage: 92,
    studentsPresent: 23,
    totalStudents: 25,
  },
];
